# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-12 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 12, 16, 16, 3, 102050, tzinfo=utc)),
        ),
    ]
